export const UPDATE_DATA_REQUESTED = "UPDATE_DATA_REQUESTED";

export const ADD_TODO_REQUESTED = "ADD_TODO_REQUESTED";
export const ADD_TODO_FAILED = "ADD_TODO_FAILED";
export const ADD_TODO_SUCCESSED = "ADD_TODO_SUCCESSED";

export const GET_TODO_LIST_REQUESTED = "GET_TODO_LIST_REQUESTED";
export const GET_TODO_LIST_SUCCESSED = "GET_TODO_LIST_SUCCESSED";
export const GET_TODO_LIST_FAILED = "GET_TODO_LIST_FAILED";

export const DELETE_TODO_LIST_REQUESTED = "DELETE_TODO_LIST_REQUESTED";
export const DELETE_TODO_LIST_SUCCESSED = "DELETE_TODO_LIST_SUCCESSED";
export const DELETE_TODO_LIST_FAILED = "DELETE_TODO_LIST_FAILED";
